/* hard coded array of werds */
var words = {
    'easy':[
        'roller',
        'reply',
        'rule',
        'rogue',
        'roman',
        'royal',
        'rural',
        'rinse',
        'risen',
        'reign',
        'redux',
        'rodeo'
    ],

    'medium':[
        'rococo',
        'rhythm',
        'radiate',
        'raggedy',
        'raining',
        'ramble',
        'rampage',
        'ranger',
        'ransack',
        'rating',
        'reverse',
        'review',
        'ridigly',
        'rikshaw',
        'rising',
        'risotto',
        'rockery',
        'running',
        'racoon',
        'roboto',
        'raclette',
        'rubicon',
        'radiuses',
        'renegade',
        'rawhided',
        'ruckling',
        'rugulose',
        'rubellas',
    ],

    'hard':[
        'repatriate',
        'romanticism',
        'rheumatism',
        'rathskeller',
        'rotundities',
        'ruffianisms',
        'radiative',
        'rainwater',
        'realistic',
        'recessive',
        'recording',
        'righteous',
        'rigmarole',
        'rowdiness',
        'radiometer',
        'reversible',
        'ringmaster',
        'repellency',
        'raunchiness',
        'rhinestones',
    ],

    'superhard': [
        'radionuclide',
        'repellencies',
        'rhizospheres',
        'reconnaissance',
        'reflectivities',
        'repudiationist',
        'rumormongering',
        'rhombencephalon',
        'retinoblastimas',
        'radiosensitivities',
        'radiochromatograms',
        'roentgenologically',
        'ribonucleoproteins'
    ],
};

var css = {
    'easy':[
        'width: 100px;',
        'height: 100px;',
        'margin: auto',
        'display: none;',
        'display: block;',
        'display: table;',
        'display: flex',
        'float: right;',
        'float: left;',
        'float: none;',
        'font-size: 12px;',
        'line-height: 20px;',
        'color: black;',
        'cursor: hand;',
        'cursor: pointer;',
    ],

    'medium':[
        'display: inline-block;',
        'font-style: italic;',
        'text-align: center;',
        'text-align: left;',
        'text-align: right;',
        'text-align: justify;',
        'border: 1px solid black;',
        'list-style: none',
        'position: absolute',
        'position: relative',
        'position: fixed;',
        'visibility: hidden;',
        'font-weight: bold;',
        'font-weight: 300;',
        'font-weight: 400;',
        'font-weight: 500;',
        'font-weight: normal;',
    ],

    'hard':[
        'justify-content: space-around;',
        'justify-content: flex-start;',
        'justify-content: flex-end;',
        'margin: 0px 12px 8px 4px;',
        'padding: 0px 12px 8px 4px;',
        'text-decoration: line-through;',
        'display: table-row-group;',
        'list-style-type: disc;',
    ],

    'superhard': [
        'box-shadow: 0px 5px #000000',
        'transform: translateY(5px);',
        'animation-timing-function: ease-in;',
        'border-right-color: transparent;',
        'background: url(../img/logo.svg) no-repeat top left;',
    ],
};