/* hard coded array of werds */
var words = {
    'easy':[
        'roller',
        'reply',
        'rule',
        'rogue',
        'roman',
        'royal',
        'rural',
        'rinse',
        'risen',
        'reign',
        'redux',
        'rodeo',
        'rally',
        'rope',
        'recluse',
        'rabbit',
    ],

    'medium':[
        'rococo',
        'rhythm',
        'radiate',
        'raggedy',
        'rabbles',
        'racquet',
        'radiale',
        'radicle',
        'rapport',
        'raining',
        'ramble',
        'rampage',
        'ranger',
        'ransack',
        'rating',
        'reverse',
        'review',
        'ridigly',
        'rikshaw',
        'rising',
        'risotto',
        'rockery',
        'running',
        'racoon',
        'roboto',
        'raclette',
        'rubicon',
        'radiuses',
        'renegade',
        'rawhided',
        'ruckling',
        'rugulose',
        'rubellas',
        'royalty'
    ],

    'hard':[
        'repatriate',
        'romanticism',
        'rheumatism',
        'rathskeller',
        'rotundities',
        'ruffianisms',
        'radiative',
        'rainwater',
        'realistic',
        'recessive',
        'recording',
        'righteous',
        'rigmarole',
        'rowdiness',
        'radiometer',
        'reversible',
        'ringmaster',
        'repellency',
        'raunchiness',
        'rhinestones',
        'ramparting',
        'rangelands',
        'ratcheting',
        'rationally',
        'refinanced',
        'reinitiate',
        'revalorize',
        'riversides',
        'rosinesses',
        'rotational',
        'rumination',
        'restaurant',
        'restlessly',
        'repertoire',
        'repolarize',
        'remorseful',
        'remunerate',
    ],

    'superhard': [
        'radionuclide',
        'radicalization',
        'reattributions',
        'rebelliousness',
        'reintegrations',
        'repartitioning',
        'revolutionists',
        'retrogressing',
        'retroflexions',
        'radiochemical',
        'radicalnesses',
        'radiobiologic',
        'radioisotopes',
        'ridiculousness',
        'rigorousnesses',
        'rootlessnesses',
        'repellencies',
        'rhizospheres',
        'reconnaissance',
        'reflectivities',
        'recentrifuged',
        'receptiveness',
        'repudiationist',
        'rumormongering',
        'rhombencephalon',
        'retinoblastimas',
        'radiosensitivities',
        'radiochromatograms',
        'roentgenologically',
        'ribonucleoproteins',
        'rhabdomyosarcoma',
        'respectabilities',
        'relentlessnesses',
        'representativenesses',
        'radiopharmaceuticals',
        'reconceptualization',
    ],
};

var phrases = {
    'easy':[
        'take your dog',
        'for a walk',
        'around the corner',
        'ball of yarn',
        'wash my car',
        'call my mother',
        'hello excuse me',
        'mocha latte please',
        'down the street',
        'over the bridge',
        'by the path',
        'a small luggage',
        'a portable charger',
        'cardigan backyardigan',
        'seize the day',
        'never give up',
        'make my day',
        'i am groot',
        'just keep swimming',
        'bond. james bond',
        'e.t phone home',
        'this is sparta!'
    ],

    'medium':[
        'keep up with the pace',
        'thanks for your help',
        'sorry for being late',
        'fasten your seat belts',
        'what dreams are made of',
        'top of the world',
        'no place like home',
        'i want to be alone',
        'i see dead people',
        'i want to play a game',
        'i volunteer as tribute',
        'you shall not pass!',
        'hasta la vista, baby',
        'ogres are like onions',
        'to infinity and beyond!',
        'get off my lawn',
        'that is so fetch',
    ],

    'hard':[
        'may the force be with you',
        'houston, we have a problem',
        'elementary, my dear watson',
        'nobody puts baby in a corner',
        'you have bewitched me, body and soul',
        'i just wanted to take another look at you',
        'so you think you\'re really pretty',
        'with great power comes great responsibility',
        'keep the change ya filthy animal',
        'if you are good, life is good',
        'honey? where\'s my super suit?',
        'what is this? a center for ants?',
        'you sit on a throne of lies',
        'florals? for spring? ground breaking',
        'get in loser! we\'re going shopping!',
        'wow this is a goddamn greek tragedy',
        'welcome back, cowboy',
        'here\'s looking at you, kid',
        'she asked me how to spell orange',
        'and none for gretchen wieners bye',
        'one time, she punched me in the face. it was awesome.',
        'on wednesdays we wear pink',
        'you smell like a baby prostitute',

    ],

    'superhard': [
        'keep your friends close, but enemies closer',
        'get your stinking paws off me, you damned dirty ape',
        'look at me, look at me. i am the captain now',
        'how many of you have ever felt personally victimised by regina george?',
        'there\'s a 30 percent chance that it\'s already raining',
        'let us step into the night and pursue that flighty temptress, adventure',
        'we are only as strong as we are united, as weak as we are divided',
        'mama always said life was like a box of chocolates, you never know what you\'re gonna get',
        'the first rule of fight club is you do not talk about fight club',
        'magic mirror on the wall, who is the fairest one of all?',
        'they may take our lives, but they\'ll never take our freedom!',
        'that\'s my secret, captain: i\'m always angry',
        'this is the day you will always remember as the day you almost caught Captain Jack Sparrow!',
        'gretchen stop trying to make fetch happen, it\'s not going to happen!',
        'ex-boyfriends are off-limits to friends. that\’s just, like, the rules of feminism.',
        'if you\’re from Africa, why are you white?'
    ],
};

var css = {
    'easy':[
        'width: 100px;',
        'height: 100px;',
        'margin: auto;',
        'display: none;',
        'display: block;',
        'display: table;',
        'display: flex;',
        'float: right;',
        'float: left;',
        'float: none;',
        'font-size: 12px;',
        'line-height: 20px;',
        'color: black;',
        'cursor: hand;',
        'cursor: pointer;',
        'top: 10px;',
        'right: 20px;',
        'left: 15px;',
        'bottom: 10px;',
        'color: pink;',
        'color: coral;',
        'background: red;',
        'background: yellow;',
        'background: pink;',
        'z-index: 1;',
    ],

    'medium':[
        'display: inline-block;',
        'font-style: italic;',
        'text-align: center;',
        'text-align: left;',
        'text-align: right;',
        'text-align: justify;',
        'border: 1px solid black;',
        'list-style: none;',
        'position: absolute;',
        'position: relative;',
        'position: fixed;',
        'visibility: hidden;',
        'font-weight: bold;',
        'font-weight: 300;',
        'font-weight: 400;',
        'font-weight: 500;',
        'font-weight: normal;',
        'border-radius: 50%;',
        'padding-top: 20px;',
        'padding-bottom: 15px;',
        'padding-right: 20px;',
        'padding-left: 15px;',
        'opacity: 0.8;',
        'min-width: 100%;',
        'min-height: 500px;',
        'font-weight: 100;',
        'flex-grow: 3;',
        'flex-grow: 1;',
    ],

    'hard':[
        'justify-content: space-around;',
        'justify-content: flex-start;',
        'justify-content: flex-end;',
        'text-decoration: line-through;',
        'display: table-row-group;',
        'list-style-type: disc;',
        'flex-direction: row-reverse;',
        'background-origin: content-box;',
        'background-repeat: no-repeat;',
        'background-position: center;',
        'border-collapse: collapse;',
        'border-collapse: separate;',
        'animation-direction: alternate;',
        'font-variant: small-caps;',
        'vertical-align: text-bottom;',
        'flex-flow: row-reverse wrap;',
        'animation-play-state: paused;',
        'animation-play-state: running;',
    ],

    'superhard': [
        'box-shadow: 0px 5px #000000;',
        'margin: 0px 12px 8px 4px;',
        'padding: 0px 12px 8px 4px;',
        'transform: translateY(5px);',
        'animation-timing-function: ease-in;',
        'border-right-color: transparent;',
        'border-left-color: transparent;',
        'background: url(../img/logo.svg) no-repeat top left;',
        'border-bottom-left-radius: 20px;',
        'border-bottom-right-radius: 15px;',
        'border-top-left-radius: 20px;',
        'border-top-right-radius: 15px;',
        'transition-timing-function: linear;',
        'transition-timing-function: ease-in-out;',
        'transition-timing-function: step-start;',
        'transition-timing-function: step-end;',
        'transition-timing-function: linear;',
        'animation-iteration-count: infinite;',
        'background: url(../img/footer.jpg);',
        'filter: grayscale(100%);',
        'filter: blur(50%);',
    ],
};

