/* hard coded array of werds */
var words = {
    'easy':[
        'roller',
        'reply',
        'rule',
        'rogue',
        'roman',
        'royal',
        'rural',
        'rinse',
        'risen',
        'reign',
        'redux',
        'rodeo'
    ],

    'medium':[
        'rococo',
        'rhythm',
        'radiate',
        'raggedy',
        'raining',
        'ramble',
        'rampage',
        'ranger',
        'ransack',
        'rating',
        'reverse',
        'review',
        'ridigly',
        'rikshaw',
        'rising',
        'risotto',
        'rockery',
        'running',
        'racoon',
        'roboto',
        'raclette',
        'rubicon',
        'radiuses',
        'renegade',
        'rawhided',
        'ruckling',
        'rugulose',
        'rubellas',
    ],

    'hard':[
        'repatriate',
        'romanticism',
        'rheumatism',
        'rathskeller',
        'rotundities',
        'ruffianisms',
        'radiative',
        'rainwater',
        'realistic',
        'recessive',
        'recording',
        'righteous',
        'rigmarole',
        'rowdiness',
        'radiometer',
        'reversible',
        'ringmaster',
        'repellency',
        'raunchiness',
        'rhinestones',
    ],

    'superhard': [
        'radionuclide',
        'repellencies',
        'rhizospheres',
        'reconnaissance',
        'reflectivities',
        'repudiationist',
        'rumormongering',
        'rhombencephalon',
        'retinoblastimas',
        'radiosensitivities',
        'radiochromatograms',
        'roentgenologically',
        'ribonucleoproteins'
    ],
};

var css = {
    'easy':[
        'display: none;',
        'display: block;',
        'display: inline-block;',
        'float: right;',
        'float: left;',
        'float: none;',
    ],

    'medium':[
        'font-style: italic;',
        'text-align: center;',
        'text-align: left;',
        'text-align: right;',
        'text-align: justify;',
    ],

    'hard':[
        'margin: 0px 12px 8px 4px;',
        'text-decoration: line-through;',
        'display: table-row-group;',
        'list-style-type: disc;',
    ],

    'superhard': [
        'radionuclide',
        'repellencies',
        'rhizospheres',
        'reconnaissance',
        'reflectivities',
        'repudiationist',
        'rumormongering',
        'rhombencephalon',
        'retinoblastimas',
        'radiosensitivities',
        'radiochromatograms',
        'roentgenologically',
        'ribonucleoproteins'
    ],
};